"""empty message

Revision ID: f6e5ef548d60
Revises: 4f8b70612178
Create Date: 2020-08-22 22:40:22.334983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6e5ef548d60'
down_revision = '4f8b70612178'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'contact', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contact', type_='foreignkey')
    # ### end Alembic commands ###
